# Window setting
[window]
padding = { x = 5, y = 5 } # Padding around the terminal content
opacity = 0.0 # Window opacity (0.0 - 1.0)
decorations = "full" # Window decorations (full, transparent, none)

# Font settings
[font]
size = 16.0
#[font.normal]
#family = "Fixedsys Excelsior 3.01"
#style = "Regular"
#[font.bold]
#family = "Fixedsys Excelsior 3.01"
#style = "Bold"
#[font.italic]
#family = "Fixedsys Excelsior 3.01"
#style = "Italic"
#[font.bold_italic]
#family = "Fixedsys Excelsior 3.01"
#style = "Bold Italic"

# Color scheme
[colors]
draw_bold_text_with_bright_colors = true
[colors.primary]
background = "#0E150E"
foreground = "#BFF6BF" 
[colors.normal]
    black = '#000000'   # Black
    red = '#ff5555'     # Bright Red
    green = '#41EC55'   # Bright Green
    yellow = '#f1fa8c'  # Bright Yellow
    blue = '#bd93f9'    # Bright Blue
    magenta = '#ff79c6'  # Bright Magenta
    cyan = '#8be9fd'     # Bright Cyan
    white = '#f8f8f2'    # Bright White

  [colors.bright]
    black = '#6272a4'   # Bright Black (Gray)
    red = '#ff5555'     # Bright Red
    green = '#41EC55'   # Bright Green
    yellow = '#f1fa8c'  # Bright Yellow
    blue = '#bd93f9'    # Bright Blue
    magenta = '#ff79c6'  # Bright Magenta
    cyan = '#8be9fd'     # Bright Cyan
    white = '#ffffff'    # Bright White

# Scrolling settings
[scrolling]
history = 10000 # Maximum number of lines in scrollback buffer
multiplier = 3 # Number of lines scrolled per increment

# Key bindings
[keyboard]
bindings = [
  { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }, # Spawn new instance
  { key = "Space", mods = "Control|Shift", action = "ToggleViMode" }, # Toggle Vi mode
]
